#pragma once
static const char* emitAsGamepadEvent_js =
"function(evt, index, axes, buttons) {\n"
"	if(evt.repeat)\n"
"		return;\n"
"\n"
"	const self = arguments.callee;\n"
"	if(!('state' in self))\n"
"		self.state = {};\n"
"	if(!(index in self.state)) {\n"
"		const state = self.state[index] = { axes:[], buttons:[] };\n"
"		if(axes)\n"
"			for(var i=0; i<axes.length; i+=2)\n"
"				state.axes.push(0);\n"
"		if(buttons)\n"
"			for(var i=0; i<buttons.length; ++i)\n"
"				state.buttons.push(false);\n"
"		this.emit('gamepad', {index:index, name:'keyboard', type:'connect', axes:state.axes.length, buttons:state.buttons.length});\n"
"	}\n"
"\n"
"	const state = self.state[index];\n"
"	const keydown = evt.type==='keydown';\n"
"	if(!keydown && evt.type!=='keyup')\n"
"		return;\n"
"\n"
"	if(axes) for(var i=0; i<axes.length; ++i) {\n"
"		if(evt.key !== axes[i])\n"
"			continue;\n"
"		const axis = Math.floor(i/2), value = (i%2)?1:-1;\n"
"		if(keydown) {\n"
"			if(state.axes[axis]===value)\n"
"				return;\n"
"		}\n"
"		else if(state.axes[axis]===0 || state.axes[axis]!==value)\n"
"			return;\n"
"		state.axes[axis] = keydown ? value : 0;\n"
"		return this.emit('gamepad', {index:index, name:'keyboard', type:'axis', axis:axis, value:state.axes[axis]});\n"
"	}\n"
"\n"
"	if(buttons) for(var i=0; i<buttons.length; ++i) {\n"
"		const key = (typeof buttons[i] === 'object') ? buttons[i].key : buttons[i];\n"
"		const location = (typeof buttons[i] === 'object') ? buttons[i].location : 0;\n"
"		if(evt.key === key && state.buttons[i]!=keydown && (location===0 || evt.location===location)) {\n"
"			state.buttons[i]=keydown;\n"
"			return this.emit('gamepad', {index:index, name:'keyboard', type:'button', button:i, value:keydown?1:0});\n"
"		}\n"
"	}\n"
"}\n";

static const char* utils_js = 
"({\n"
"	lpad: function(value, numDigits, char) {\n"
"		if(char===undefined)\n"
"			char = '0';\n"
"		var s = ''+value;\n"
"		if(value>=0)\n"
"			while(s.length<numDigits)\n"
"				s = char+s;\n"
"		return s;\n"
"	},\n"
"	randf: function(v1, v2) {\n"
"		if(v2===undefined) { v2=v1; v1=0; }\n"
"		return v1+(Math.random()*(v2-v1));\n"
"	},\n"
"	randi: function(v1, v2) {\n"
"		return Math.floor(this.randf(v1,v2));\n"
"	},\n"
"	distSqr: function(x1, y1, x2, y2) {\n"
"		return Math.pow(x2-x1, 2) + Math.pow(y2-y1, 2);\n"
"	},\n"
"	dist: function(x1, y1, x2, y2) {\n"
"		return Math.sqrt(Math.pow(x2-x1, 2) + Math.pow(y2-y1, 2));\n"
"	},\n"
"	clamp: function(value, min, max) {\n"
"		return value<min ? min : value>max ? max : value;\n"
"	},\n"
"})\n";
